apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tb2-ext-group-10
namePrefix: tb2-ext-
nameSuffix: -group-10
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
      name: tb2-ext
    patch: |-
      - op: replace
        path: /metadata/name
        value: tb2-ext-group-10
